project:
  type: website

website:
  title: "Bordar Space"
  site-url: https://mohsen-saki.github.io/bordar_space/
  favicon: images/logo.png
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: sandstone
    css: styles.css
